### ISSUE TITLE
WikiCite 2018

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#212]
things that would be nice to have done before [WikiCite 2018](https://meta.wikimedia.org/wiki/WikiCite_2018):
- [ ] [create the missing entities to cover all ISBNs in Wikipedia](https://github.com/inventaire/inventaire/issues/183)
- [ ] produce statistics on the number of links made to works and authors known by Wikidata within those Inventaire entities
- [x] [be able to import an Inventaire entity to Wikidata](https://github.com/inventaire/inventaire/issues/104)
- [ ] have some prototype of [entities collections](https://github.com/inventaire/inventaire/issues/184) working(?)
- [x] prepare for a discussion on [moving entities to a federated Wikibase](https://github.com/inventaire/inventaire/issues/186)
- [x] federated Inventaire SPARQL endpoint
